# Generated by Django 3.1.3 on 2021-11-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
